FROM php:7.4-apache
RUN apt-get update && apt-get install -y \
        libpq-dev curl
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install pgsql
RUN docker-php-ext-configure pdo_pgsql && docker-php-ext-install pdo_pgsql sockets
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions pcntl
RUN a2enmod rewrite
COPY ./app_admin/backend /usr/src/app_admin
COPY ./config/vhost.conf /etc/apache2/sites-available/000-default.conf
WORKDIR /usr/src/app_admin/
RUN chown -R www-data:www-data .
EXPOSE 8080
CMD [ "php", "./public/index.php", "start" ]
