{
  "version": "3.1",
  "volumes": {
    "postgres_data": { },
    "nginx_data": { },
    "mongo_data": { },
    "rabbitmq_data": { }
  },
  "services": {
    "postgres": {
      "image": "postgres",
      "volumes": [
          "postgres_data:/var/lib/postgresql/data/"
      ],
      "env_file": ".env",
      "ports": [
          "${POSTGRES_PORT}"
      ],
    },
    "admin_panel": {
      "image": "yiisoftware/yii2-php:7.4-apache",
      "volumes": [
          "~/.composer:/root/.composer",
          "~/.composer-docker/cache:/root/.composer/cache:delegated",
          "./admin_panel/backend/basic:/app:delegated",
          "./admin_panel/backend/basic:/var/www"
      ],
      "ports": [
          "${YII_POST_EXT}:${YII_POST_INT}"
      ],
      "env_file": ".env",
      "depends_on": [
          "postgres",
          "rabbit"
      ]
    },
    "mongo": {
      "image": "mongo",
      "hostname": "${MONGODB_HOST}",
      "restart": "always",
      "env_file": ".env",
      "ports": [
          "${MONGODB_PORT}:${MONGODB_PORT}"
      ],
      "environment": {
        "MONGO_INITDB_ROOT_USERNAME": "${MONGODB_USER}",
        "MONGO_INITDB_ROOT_PASSWORD": "${MONGODB_PASSWORD}",
      },
      "volumes": [
          "mongo_data:/data/db/"
      ]
    },
    "mongo-express": {
      "image": "mongo-express",
      "restart": "always",
      "ports": [
          "8081:8081"
      ],
      "env_file": ".env",
      "environment": {
        "ME_CONFIG_MONGODB_AUTH_DATABASE": "${MONGODB_USER}",
        "ME_CONFIG_MONGODB_ADMINUSERNAME": "${MONGODB_USER}",
        "ME_CONFIG_MONGODB_ADMINPASSWORD": "${MONGODB_PASSWORD}",
        "ME_CONFIG_MONGODB_ENABLE_ADMIN": "true"
      },
      "links": [
          "mongo"
      ]
    },
    "shop": {
      "build": {
        "context": "./",
        "dockerfile": "Dockerfile-client-api"
      },
      "ports": [
          "${CLIENT_PORT_EXT}:${CLIENT_PORT_EXT}"
      ],
      "env_file": ".env",
      "depends_on": [
          "mongo",
          "rabbit"
      ]
    },
    "rabbit": {
      "build": {
        "context": "./",
        "dockerfile": "Dockerfile-rabbit"
      },
      "env_file": ".env",
      "hostname": "${RABBIT_HOST}",
      "ports": [
          "${RABBIT_PORT}:${RABBIT_PORT}",
          "${RABBIT_PORT2}:${RABBIT_PORT2}"
      ],
      "volumes": [
          "rabbitmq_data:/var/lib/rabbitmq_data/data/"
      ],
      "healthcheck": {
        "test": "rabbitmq-diagnostics -q ping",
        "interval": "5s",
        "timeout": "15s",
        "retries": "5"
      }
    },
    "consumer": {
      "build": {
        "context": "./",
        "dockerfile": "Dockerfile-consumer"
      },
      "ports": [
          "${APACHE_PORT_EXT_X}0:${APACHE_PORT_INT_X}0"
      ],
      "links": [
          "rabbit",
          "mongo"
      ],
      "depends_on": [
          "rabbit",
          "mongo"
      ],
      "healthcheck": {
        "test": "curl -sS http://${RABBIT_HOST}:${RABBIT_PORT2} || exit 1",
        "interval": "5s",
        "timeout": "15s",
        "retries": "5"
      },
      "env_file": ".env",
    }
  }
}
