{
  "version": "3.1",
  "volumes": {
    "postgres_data": { },
    "nginx_data": { }
  },
  "services": {
    "postgres": {
      "image": "postgres",
      "volumes": [
          "postgres_data:/var/lib/postgresql/data/"
      ],
      "env_file": ".env",
      "ports": [
          "${POSTGRES_PORT}"
      ],
    },
    "admin_panel": {
      "image": "yiisoftware/yii2-php:7.4-apache",
      "volumes": [
          "~/.composer:/root/.composer",
          "~/.composer-docker/cache:/root/.composer/cache:delegated",
          "./admin_panel/backend/basic:/app:delegated",
          "./admin_panel/backend/basic:/var/www"
      ],
      "ports": [
          "${YII_POST_EXT}:${YII_POST_INT}"
      ],
      "env_file": ".env",
      "depends_on": [
          "postgres"
      ]
    },
    "front": {
      "build": {
        "context": "./",
        "dockerfile": "Dockerfile-admin-front"
      },
      "ports": [
          "${FRONT_PORT}:${FRONT_PORT}"
      ]
    }
  }
}
