FROM php:7.4-cli
RUN docker-php-ext-install sockets && apt-get update \
    && apt-get install -y libevent-dev libcurl4-openssl-dev pkg-config libssl-dev libonig-dev curl zip unzip \
    && pecl install event mongodb \
    && docker-php-ext-enable event mongodb \
    && docker-php-ext-install mbstring pcntl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY ./client_shop/backend /var/www/
WORKDIR /var/www
RUN composer install
CMD ["php", "./src/app.php", "start"]