FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yqq && apt-get install -yqq \
	software-properties-common build-essential

RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php > /dev/null
RUN apt-get update -yqq && apt-get install -yqq \
    php7.4-dev php7.4-curl php-pear pkg-config libevent-dev

RUN printf "\n\n /usr/lib/x86_64-linux-gnu/\n\n\nno\n\n\n" | \
    pecl install event && \
    echo "extension=event.so" > /etc/php/7.4/cli/conf.d/event.ini

RUN apt-get install -y netcat libzip-dev zip  libcurl4-openssl-dev pkg-config libssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb && php -i | grep mongodb

COPY ./client_shop/backend /var/www/
WORKDIR /var/www

CMD php ./src/app.php start