FROM php:7.4-cli
RUN apt-get update -y \
    && apt-get install -y netcat  libzip-dev zip libcurl4-openssl-dev pkg-config libssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb
COPY ./broker /usr/src/mybroker
WORKDIR /usr/src/mybroker
CMD ["php", "./src/receive.php"]